/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as BalanceRouteImport } from './routes/balance'

const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const BalanceRoute = BalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/balance': typeof BalanceRoute
  '/expenses': typeof ExpensesRoute
}
export interface FileRoutesByTo {
  '/balance': typeof BalanceRoute
  '/expenses': typeof ExpensesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/balance': typeof BalanceRoute
  '/expenses': typeof ExpensesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/balance' | '/expenses'
  fileRoutesByTo: FileRoutesByTo
  to: '/balance' | '/expenses'
  id: '__root__' | '/balance' | '/expenses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BalanceRoute: typeof BalanceRoute
  ExpensesRoute: typeof ExpensesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balance': {
      id: '/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof BalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  BalanceRoute: BalanceRoute,
  ExpensesRoute: ExpensesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
