/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BalanceRouteImport } from './routes/balance'
import { Route as ExpensesLiveRouteImport } from './routes/expenses/live'
import { Route as ExpensesHistoryRouteImport } from './routes/expenses/history'

const BalanceRoute = BalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesLiveRoute = ExpensesLiveRouteImport.update({
  id: '/expenses/live',
  path: '/expenses/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesHistoryRoute = ExpensesHistoryRouteImport.update({
  id: '/expenses/history',
  path: '/expenses/history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/balance': typeof BalanceRoute
  '/expenses/history': typeof ExpensesHistoryRoute
  '/expenses/live': typeof ExpensesLiveRoute
}
export interface FileRoutesByTo {
  '/balance': typeof BalanceRoute
  '/expenses/history': typeof ExpensesHistoryRoute
  '/expenses/live': typeof ExpensesLiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/balance': typeof BalanceRoute
  '/expenses/history': typeof ExpensesHistoryRoute
  '/expenses/live': typeof ExpensesLiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/balance' | '/expenses/history' | '/expenses/live'
  fileRoutesByTo: FileRoutesByTo
  to: '/balance' | '/expenses/history' | '/expenses/live'
  id: '__root__' | '/balance' | '/expenses/history' | '/expenses/live'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BalanceRoute: typeof BalanceRoute
  ExpensesHistoryRoute: typeof ExpensesHistoryRoute
  ExpensesLiveRoute: typeof ExpensesLiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/balance': {
      id: '/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof BalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/live': {
      id: '/expenses/live'
      path: '/expenses/live'
      fullPath: '/expenses/live'
      preLoaderRoute: typeof ExpensesLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/history': {
      id: '/expenses/history'
      path: '/expenses/history'
      fullPath: '/expenses/history'
      preLoaderRoute: typeof ExpensesHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  BalanceRoute: BalanceRoute,
  ExpensesHistoryRoute: ExpensesHistoryRoute,
  ExpensesLiveRoute: ExpensesLiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
